import { SourceSpecification, LayerSpecification } from "mapbox-gl";

export interface LayerMap {
  [key: string]: LayerSpecification;
}

export interface SourceMap {
  [key: string]: SourceSpecification;
}

export interface CountyData {
  fips: string
  state: string
  county: string
  total_pop: number
  total_pop_moe: number
  male_pop: number
  male_pop_moe: number
  female_pop: number
  female_pop_moe: number
  median_age: number
  median_age_moe: number
  "18_pop": number
  "18_pop_moe": number
  not_hispanic_or_latino_pop: number
  not_hispanic_or_latino_pop_moe: number
  white_alone_pop: number
  white_alone_pop_moe: number
  black_alone_pop: number
  black_alone_pop_moe: number
  am_indian_alone_pop: number
  am_indian_alone_pop_moe: number
  asian_alone_pop: number
  asian_alone_pop_moe: number
  haw_pac_alone_pop: number
  haw_pac_alone_pop_moe: number
  other_alone_pop: number
  other_alone_pop_moe: number
  hispanic_or_latino_pop: number
  hispanic_or_latino_pop_moe: number
  total_hh: number
  total_hh_moe: number
  owner_hh: number
  owner_hh_moe: number
  rent_hh: number
  rent_hh_moe: number
  median_hh_inc: number
  median_hh_inc_moe: number
  median_family_inc: number
  median_family_inc_moe: number
  median_inc: number
  median_inc_moe: number
  pov_level: number
  pov_level_moe: number
  labor_force: number
  labor_force_moe: number
  comm_drive: number
  comm_drive_moe: number
  comm_drive_alone: number
  comm_drive_alone_moe: number
  comm_pool: number
  comm_pool_moe: number
  comm_trans: number
  comm_trans_moe: number
  comm_bus: number
  comm_bus_moe: number
  comm_subway: number
  comm_subway_moe: number
  comm_rail: number
  comm_rail_moe: number
  comm_light_rail: number
  comm_light_rail_moe: number
  comm_ferry: number
  comm_ferry_moe: number
  comm_walk: number
  comm_walk_moe: number
  comm_bike: number
  comm_bike_moe: number
  comm_taxi_motor_other: number
  comm_taxi_motor_other_moe: number
  wfh: number
  wfh_moe: number
  male_armed_forces_16_19: number
  male_armed_forces_16_19_moe: number
  male_armed_forces_20_21: number
  male_armed_forces_20_21_moe: number
  male_armed_forces_22_24: number
  male_armed_forces_22_24_moe: number
  male_armed_forces_25_29: number
  male_armed_forces_25_29_moe: number
  male_armed_forces_30_34: number
  male_armed_forces_30_34_moe: number
  male_armed_forces_35_44: number
  male_armed_forces_35_44_moe: number
  male_armed_forces_45_54: number
  male_armed_forces_45_54_moe: number
  male_armed_forces_55_59: number
  male_armed_forces_55_59_moe: number
  male_armed_forces_60_61: number
  male_armed_forces_60_61_moe: number
  male_armed_forces_62_64: number
  male_armed_forces_62_64_moe: number
  male_employed_16_19: number
  male_employed_16_19_moe: number
  male_employed_20_21: number
  male_employed_20_21_moe: number
  male_employed_22_24: number
  male_employed_22_24_moe: number
  male_employed_25_29: number
  male_employed_25_29_moe: number
  male_employed_30_34: number
  male_employed_30_34_moe: number
  male_employed_35_44: number
  male_employed_35_44_moe: number
  male_employed_45_54: number
  male_employed_45_54_moe: number
  male_employed_55_59: number
  male_employed_55_59_moe: number
  male_employed_60_61: number
  male_employed_60_61_moe: number
  male_employed_62_64: number
  male_employed_62_64_moe: number
  male_employed_65_69: number
  male_employed_65_69_moe: number
  male_employed_70_74: number
  male_employed_70_74_moe: number
  male_employed_75: number
  male_employed_75_moe: number
  male_unemployed_16_19: number
  male_unemployed_16_19_moe: number
  male_unemployed_20_21: number
  male_unemployed_20_21_moe: number
  male_unemployed_22_24: number
  male_unemployed_22_24_moe: number
  male_unemployed_25_29: number
  male_unemployed_25_29_moe: number
  male_unemployed_30_34: number
  male_unemployed_30_34_moe: number
  male_unemployed_35_44: number
  male_unemployed_35_44_moe: number
  male_unemployed_45_54: number
  male_unemployed_45_54_moe: number
  male_unemployed_55_59: number
  male_unemployed_55_59_moe: number
  male_unemployed_60_61: number
  male_unemployed_60_61_moe: number
  male_unemployed_62_64: number
  male_unemployed_62_64_moe: number
  male_unemployed_65_69: number
  male_unemployed_65_69_moe: number
  male_unemployed_70_74: number
  male_unemployed_70_74_moe: number
  male_unemployed_75: number
  male_unemployed_75_moe: number
  male_not_in_labor_force_16_19: number
  male_not_in_labor_force_16_19_moe: number
  male_not_in_labor_force_20_21: number
  male_not_in_labor_force_20_21_moe: number
  male_not_in_labor_force_22_24: number
  male_not_in_labor_force_22_24_moe: number
  male_not_in_labor_force_25_29: number
  male_not_in_labor_force_25_29_moe: number
  male_not_in_labor_force_30_34: number
  male_not_in_labor_force_30_34_moe: number
  male_not_in_labor_force_35_44: number
  male_not_in_labor_force_35_44_moe: number
  male_not_in_labor_force_45_54: number
  male_not_in_labor_force_45_54_moe: number
  male_not_in_labor_force_55_59: number
  male_not_in_labor_force_55_59_moe: number
  male_not_in_labor_force_60_61: number
  male_not_in_labor_force_60_61_moe: number
  male_not_in_labor_force_62_64: number
  male_not_in_labor_force_62_64_moe: number
  male_not_in_labor_force_65_69: number
  male_not_in_labor_force_65_69_moe: number
  male_not_in_labor_force_70_74: number
  male_not_in_labor_force_70_74_moe: number
  male_not_in_labor_force_75: number
  male_not_in_labor_force_75_moe: number
  female_armed_forces_16_19: number
  female_armed_forces_16_19_moe: number
  female_armed_forces_20_21: number
  female_armed_forces_20_21_moe: number
  female_armed_forces_22_24: number
  female_armed_forces_22_24_moe: number
  female_armed_forces_25_29: number
  female_armed_forces_25_29_moe: number
  female_armed_forces_30_34: number
  female_armed_forces_30_34_moe: number
  female_armed_forces_35_44: number
  female_armed_forces_35_44_moe: number
  female_armed_forces_45_54: number
  female_armed_forces_45_54_moe: number
  female_armed_forces_55_59: number
  female_armed_forces_55_59_moe: number
  female_armed_forces_60_61: number
  female_armed_forces_60_61_moe: number
  female_armed_forces_62_64: number
  female_armed_forces_62_64_moe: number
  female_employed_16_19: number
  female_employed_16_19_moe: number
  female_employed_20_21: number
  female_employed_20_21_moe: number
  female_employed_22_24: number
  female_employed_22_24_moe: number
  female_employed_25_29: number
  female_employed_25_29_moe: number
  female_employed_30_34: number
  female_employed_30_34_moe: number
  female_employed_35_44: number
  female_employed_35_44_moe: number
  female_employed_45_54: number
  female_employed_45_54_moe: number
  female_employed_55_59: number
  female_employed_55_59_moe: number
  female_employed_60_61: number
  female_employed_60_61_moe: number
  female_employed_62_64: number
  female_employed_62_64_moe: number
  female_employed_65_69: number
  female_employed_65_69_moe: number
  female_employed_70_74: number
  female_employed_70_74_moe: number
  female_employed_75: number
  female_employed_75_moe: number
  female_unemployed_16_19: number
  female_unemployed_16_19_moe: number
  female_unemployed_20_21: number
  female_unemployed_20_21_moe: number
  female_unemployed_22_24: number
  female_unemployed_22_24_moe: number
  female_unemployed_25_29: number
  female_unemployed_25_29_moe: number
  female_unemployed_30_34: number
  female_unemployed_30_34_moe: number
  female_unemployed_35_44: number
  female_unemployed_35_44_moe: number
  female_unemployed_45_54: number
  female_unemployed_45_54_moe: number
  female_unemployed_55_59: number
  female_unemployed_55_59_moe: number
  female_unemployed_60_61: number
  female_unemployed_60_61_moe: number
  female_unemployed_62_64: number
  female_unemployed_62_64_moe: number
  female_unemployed_65_69: number
  female_unemployed_65_69_moe: number
  female_unemployed_70_74: number
  female_unemployed_70_74_moe: number
  female_unemployed_75: number
  female_unemployed_75_moe: number
  female_not_in_labor_force_16_19: number
  female_not_in_labor_force_16_19_moe: number
  female_not_in_labor_force_20_21: number
  female_not_in_labor_force_20_21_moe: number
  female_not_in_labor_force_22_24: number
  female_not_in_labor_force_22_24_moe: number
  female_not_in_labor_force_25_29: number
  female_not_in_labor_force_25_29_moe: number
  female_not_in_labor_force_30_34: number
  female_not_in_labor_force_30_34_moe: number
  female_not_in_labor_force_35_44: number
  female_not_in_labor_force_35_44_moe: number
  female_not_in_labor_force_45_54: number
  female_not_in_labor_force_45_54_moe: number
  female_not_in_labor_force_55_59: number
  female_not_in_labor_force_55_59_moe: number
  female_not_in_labor_force_60_61: number
  female_not_in_labor_force_60_61_moe: number
  female_not_in_labor_force_62_64: number
  female_not_in_labor_force_62_64_moe: number
  female_not_in_labor_force_65_69: number
  female_not_in_labor_force_65_69_moe: number
  female_not_in_labor_force_70_74: number
  female_not_in_labor_force_70_74_moe: number
  female_not_in_labor_force_75: number
  female_not_in_labor_force_75_moe: number
  hh_inc_10k: number
  hh_inc_10k_moe: number
  hh_inc_10k_15k: number
  hh_inc_10k_15k_moe: number
  hh_inc_15k_20k: number
  hh_inc_15k_20k_moe: number
  hh_inc_20k_25k: number
  hh_inc_20k_25k_moe: number
  hh_inc_25k_30k: number
  hh_inc_25k_30k_moe: number
  hh_inc_30k_35k: number
  hh_inc_30k_35k_moe: number
  hh_inc_35k_40k: number
  hh_inc_35k_40k_moe: number
  hh_inc_40k_45k: number
  hh_inc_40k_45k_moe: number
  hh_inc_45k_50k: number
  hh_inc_45k_50k_moe: number
  hh_inc_50k_60k: number
  hh_inc_50k_60k_moe: number
  hh_inc_60k_75k: number
  hh_inc_60k_75k_moe: number
  hh_inc_75k_100k: number
  hh_inc_75k_100k_moe: number
  hh_inc_100k_125k: number
  hh_inc_100k_125k_moe: number
  hh_inc_125k_150k: number
  hh_inc_125k_150k_moe: number
  hh_inc_150k_200k: number
  hh_inc_150k_200k_moe: number
  hh_inc_200k: number
  hh_inc_200k_moe: number
  owner_no_vehicle: number
  owner_no_vehicle_moe: number
  owner_1_vehicle: number
  owner_1_vehicle_moe: number
  owner_2_vehicle: number
  owner_2_vehicle_moe: number
  owner_3_vehicle: number
  owner_3_vehicle_moe: number
  owner_4_vehicle: number
  owner_4_vehicle_moe: number
  owner_5_vehicle: number
  owner_5_vehicle_moe: number
  renter_no_vehicle: number
  renter_no_vehicle_moe: number
  renter_1_vehicle: number
  renter_1_vehicle_moe: number
  renter_2_vehicle: number
  renter_2_vehicle_moe: number
  renter_3_vehicle: number
  renter_3_vehicle_moe: number
  renter_4_vehicle: number
  renter_4_vehicle_moe: number
  renter_5_vehicle: number
  renter_5_vehicle_moe: number
  family_hh: number
  family_hh_moe: number
  nonfamily_hh: number
  nonfamily_hh_moe: number
  avg_hh_size: number
  avg_hh_size_moe: number
  less_hs: number
  less_hs_moe: number
  hs_no_college: number
  hs_no_college_moe: number
  some_college: number
  some_college_moe: number
  bachelors_degree: number
  bachelors_degree_moe: number
  graduate_degree: number
  graduate_degree_moe: number
  speak_only_english: number
  speak_only_english_moe: number
  spanish: number
  spanish_moe: number
  spanish_w: number
  spanish_w_moe: number
  spanish_lim: number
  spanish_lim_moe: number
  french_haitian_or_cajun: number
  french_haitian_or_cajun_moe: number
  french_haitian_or_cajun_w: number
  french_haitian_or_cajun_w_moe: number
  french_haitian_or_cajun_lim: number
  french_haitian_or_cajun_lim_moe: number
  german_or_other_west_germanic_languages: number
  german_or_other_west_germanic_languages_moe: number
  german_or_other_west_germanic_languages_w: number
  german_or_other_west_germanic_languages_w_moe: number
  german_or_other_west_germanic_languages_lim: number
  german_or_other_west_germanic_languages_lim_moe: number
  russian_polish_or_other_slavic_languages: number
  russian_polish_or_other_slavic_languages_moe: number
  russian_polish_or_other_slavic_languages_w: number
  russian_polish_or_other_slavic_languages_w_moe: number
  russian_polish_or_other_slavic_languages_lim: number
  russian_polish_or_other_slavic_languages_lim_moe: number
  other_indo_european_languages: number
  other_indo_european_languages_moe: number
  other_indo_european_languages_w: number
  other_indo_european_languages_w_moe: number
  sother_indo_european_languages_lim: number
  sother_indo_european_languages_lim_moe: number
  korean: number
  korean_moe: number
  korean_w: number
  korean_w_moe: number
  korean_lim: number
  korean_lim_moe: number
  chinese_mandarin_cantonese: number
  chinese_mandarin_cantonese_moe: number
  chinese_mandarin_cantonese_w: number
  chinese_mandarin_cantonese_w_moe: number
  chinese_mandarin_cantonese_lim: number
  chinese_mandarin_cantonese_lim_moe: number
  vietnamese: number
  vietnamese_moe: number
  vietnamese_w: number
  vietnamese_w_moe: number
  vietnamese_lim: number
  vietnamese_lim_moe: number
  tagalog_filipino: number
  tagalog_filipino_moe: number
  tagalog_filipino_w: number
  tagalog_filipino_w_moe: number
  tagalog_filipino_lim: number
  tagalog_filipino_lim_moe: number
  other_asian_and_pacific_island_languages: number
  other_asian_and_pacific_island_languages_moe: number
  other_asian_and_pacific_island_languages_w: number
  other_asian_and_pacific_island_languages_w_moe: number
  other_asian_and_pacific_island_languages_lim: number
  other_asian_and_pacific_island_languages_lim_moe: number
  arabic: number
  arabic_moe: number
  arabic_w: number
  arabic_w_moe: number
  arabic_lim: number
  arabic_lim_moe: number
  other_and_unspecified_languages: number
  other_and_unspecified_languages_moe: number
  other_and_unspecified_languages_w: number
  other_and_unspecified_languages_w_moe: number
  other_and_unspecified_languages_lim: number
  other_and_unspecified_languages_lim_moe: number
  under_5_pop: number
  under_5_pop_moe: number
  "5_to_9_pop": number
  "5_to_9_pop_moe": number
  "10_to_14_pop": number
  "10_to_14_pop_moe": number
  "15_to_19_pop": number
  "15_to_19_pop_moe": number
  "20_to_24_pop": number
  "20_to_24_pop_moe": number
  "25_to_29_pop": number
  "25_to_29_pop_moe": number
  "30_to_34_pop": number
  "30_to_34_pop_moe": number
  "35_to_39_pop": number
  "35_to_39_pop_moe": number
  "40_to_44_pop": number
  "40_to_44_pop_moe": number
  "45_to_49_pop": number
  "45_to_49_pop_moe": number
  "50_to_54_pop": number
  "50_to_54_pop_moe": number
  "55_to_59_pop": number
  "55_to_59_pop_moe": number
  "60_to_64_pop": number
  "60_to_64_pop_moe": number
  "65_to_69_pop": number
  "65_to_69_pop_moe": number
  "70_to_74_pop": number
  "70_to_74_pop_moe": number
  "75_to_79_pop": number
  "75_to_79_pop_moe": number
  "80_to_84_pop": number
  "80_to_84_pop_moe": number
  "85_over_pop": number
  "85_over_pop_moe": number
  under_18_pov_level: number
  under_18_pov_level_moe: number
  over_65_pov_level: number
  over_65_pov_level_moe: number
  mean_hh_inc: number
  mean_hh_inc_moe: number
  mean_family_inc: number
  mean_family_inc_moe: number
  avg_family_size: number
  avg_family_size_moe: number
  co_name: string
  buffer_bbox: string
  existing_trail_mi: number
  planned_trail_mi: number
  freight_rail_mi: number
  highway_mi: number
  unique_freight_centers: number
  fy25_pa_lines: number
  fy26_nj_lines: number
  fy25_pa_points: number
  fy26_nj_points: number
  septa_bus_stops: number
  septa_bus_routes_mi: number
  njt_bus_stops: number
  njt_bus_routes_mi: number
  passenger_rail_stations: number
  passenger_rail_mi: number
  pop15: number
  pop20: number
  pop25: number
  pop30: number
  pop35: number
  pop40: number
  pop45: number
  pop50: number
  emp15: number
  emp20: number
  emp25: number
  emp30: number
  emp35: number
  emp40: number
  emp45: number
  emp50: number
  popabs50: number
  poppct50: number
  empabs50: number
  emppct50: number
  total_acres: number
  agriculture_acres: number
  commercial_acres: number
  industrial_acres: number
  institutional_acres: number
  military_acres: number
  mining_acres: number
  recreation_acres: number
  residential_acres: number
  transportation_acres: number
  undeveloped_acres: number
  utility_acres: number
  water_acres: number
  wooded_acres: number
  road_pm2_good: number
  road_pm2_fair: number
  road_pm2_poor: number
  road_iri_good: number
  road_iri_fair: number
  road_iri_poor: number
  road_dot_index_good: number
  road_dot_index_fair: number
  road_dot_index_poor: number
  bridge_all_good: number
  bridge_all_fair: number
  bridge_all_poor: number
  bridge_nhs_good: number
  bridge_nhs_fair: number
  bridge_nhs_poor: number
  bridge_nonnhs_good: number
  bridge_nonnhs_fair: number
  bridge_nonnhs_poor: number
  bev: number
  phev: number
  total_ev: number
  other_fuel: number
  total_ldv: number
  pct_ev_ldv: number
  change_ev: number
  pct_change_ev: number
  change_ldv: number
  pct_change_ldv: number
  percent_cost_burdened: number
}
